---
- hosts: all
  user: root
  gather_facts: False
  pre_tasks:
  - name: Install python for Ansible
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    register: output
    changed_when: output.stdout != ""
  vars_files:
   - vars/main.yml
  pre_tasks:
  - name: installing python for packer
    raw: apt-get -y install python
  tasks:
  - name: update cache
    apt:
      update_cache: true
      upgrade: true
  - name: install samba
    apt:
      pkg: samba
      state: present

  - name: check samba is well installed
    command: whereis samba
    register: result

  - debug: var=result.stdout_lines

  - name: create sambauser
    user:
      name={% raw %}{{sambauser}}{% endraw %}
      password={% raw %}{{password |password_hash(‘sha512’)}}{% endraw %}

  - name: create samba folder
    file:
      path: /home/sambauser/sambashare
      state: directory

  - name: create bottom line
    blockinfile:
      path: /etc/samba/smb.conf
      block: |
        [global]
          idmap config * : backend = tdb

        [sambashare]
          comment = Samba on Ubuntu
          path = /home/sambauser/sambashare
          public= yes
          read only = no
          browsable = yes
          guest ok = yes
      backup: yes
